package ru.yoursweet667.uno.web.model;

public enum EventType {
    PLAYER_PLAYED_A_CARD, FIRST_CARD_TURNED_UP, PLAYER_TAKES_INITIAL_CARDS,
    PLAYER_TOOK_A_CARD, PLAYER_JOINED_THE_GAME, PLAYER_LEFT_THE_GAME, GAME_STARTED,
    GAME_ENDED, TURN_BEGINS, TURN_ENDS, SKIP_TURN
}
